# Add 'repo' label to any root file changes
repo:
- '*'

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
- any: ['*.js', '!docs/*']

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
- any: ['*.js']
  all: ['!.css', '!*.html']
